[workspace]
members = [
    "crates/examples/triangle_basic",
    "crates/examples/triangle_advanced",
    "crates/examples/shadows",
    "crates/examples/reflections",
    "crates/libs/app",
    "crates/libs/gltf",
    "crates/libs/gui",
    "crates/libs/vulkan",
]
